# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "nfrb"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Davide Guerri"]
  s.date = "2012-03-04"
  s.description = "Nfrb is a very simple yet fast gem that can be used to parse nfcapd files."
  s.email = "davide.guerri@gmail.com"
  s.extensions = ["ext/rb_nfrb/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "ext/rb_nfrb/README.files",
    "ext/rb_nfrb/config.h",
    "ext/rb_nfrb/dnc/nffile_inline.c",
    "ext/rb_nfrb/extconf.rb",
    "ext/rb_nfrb/fts_compat.c",
    "ext/rb_nfrb/fts_compat.h",
    "ext/rb_nfrb/lzoconf.h",
    "ext/rb_nfrb/lzodefs.h",
    "ext/rb_nfrb/minilzo.h",
    "ext/rb_nfrb/nf_common.h",
    "ext/rb_nfrb/nffile.c",
    "ext/rb_nfrb/nffile.h",
    "ext/rb_nfrb/nfrb.c",
    "ext/rb_nfrb/nfx.c",
    "ext/rb_nfrb/nfx.h",
    "ext/rb_nfrb/util.c",
    "ext/rb_nfrb/util.h",
    "lib/nfrb.rb",
    "lib/nfrb/version.rb",
    "nfrb.gemspec",
    "test/helper.rb",
    "test/test_nfrb.rb"
  ]
  s.homepage = "http://github.com/dguerri/nfrb"
  s.licenses = ["BSD license"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Nfrb: nfcapd files parser."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 2.4.2"])
      s.add_development_dependency(%q<rake-compiler>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 2.4.2"])
      s.add_dependency(%q<rake-compiler>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 2.4.2"])
    s.add_dependency(%q<rake-compiler>, [">= 0"])
  end
end

